// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250517192018_AddMig")]
    partial class AddMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Server.Entities.AcademicYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AcademicYear");
                });

            modelBuilder.Entity("Server.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ApplicationStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScholarshipId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationStatusId");

                    b.HasIndex("ScholarshipId");

                    b.HasIndex("StudentId");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("Server.Entities.ApplicationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationDocument");
                });

            modelBuilder.Entity("Server.Entities.ApplicationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationStatus");
                });

            modelBuilder.Entity("Server.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Server.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CountryId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Server.Entities.EligibilityCriteria", b =>
                {
                    b.Property<int>("EligibilityCriteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CriteriaDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EligibilityCriteriaId");

                    b.ToTable("EligibilityCriteria");
                });

            modelBuilder.Entity("Server.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScholarshipId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScholarshipId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Server.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Server.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Emri = "Student"
                        },
                        new
                        {
                            Id = 2,
                            Emri = "Provider"
                        },
                        new
                        {
                            Id = 3,
                            Emri = "Admin"
                        });
                });

            modelBuilder.Entity("Server.Entities.Scholarship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AcademicYearId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplyLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EligibilityCriteriaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScholarshipCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScholarshipTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("EligibilityCriteriaId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ScholarshipCategoryId");

                    b.HasIndex("ScholarshipTypeId");

                    b.ToTable("Scholarship");
                });

            modelBuilder.Entity("Server.Entities.ScholarshipAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AwardDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScholarshipId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScholarshipId");

                    b.HasIndex("StudentId");

                    b.ToTable("ScholarshipAward");
                });

            modelBuilder.Entity("Server.Entities.ScholarshipCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScholarshipCategory");
                });

            modelBuilder.Entity("Server.Entities.ScholarshipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScholarshipType");
                });

            modelBuilder.Entity("Server.Entities.StudentLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StudentLevel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = "Bachelor"
                        },
                        new
                        {
                            Id = 2,
                            Level = "Master"
                        },
                        new
                        {
                            Id = 3,
                            Level = "PhD"
                        },
                        new
                        {
                            Id = 4,
                            Level = "High School Graduate"
                        },
                        new
                        {
                            Id = 5,
                            Level = "Training Participant"
                        });
                });

            modelBuilder.Entity("Server.Entities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("University");
                });

            modelBuilder.Entity("Server.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Server.Entities.UserActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActivityType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserActivityLog");
                });

            modelBuilder.Entity("Server.Entities.Admin", b =>
                {
                    b.HasBaseType("Server.Entities.User");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("RoleId");

                    b.ToTable("User", t =>
                        {
                            t.Property("RoleId")
                                .HasColumnName("Admin_RoleId");
                        });

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Server.Entities.Provider", b =>
                {
                    b.HasBaseType("Server.Entities.User");

                    b.Property<int?>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CountryId");

                    b.HasIndex("RoleId");

                    b.ToTable("User", t =>
                        {
                            t.Property("RoleId")
                                .HasColumnName("Provider_RoleId");
                        });

                    b.HasDiscriminator().HasValue("Provider");
                });

            modelBuilder.Entity("Server.Entities.Student", b =>
                {
                    b.HasBaseType("Server.Entities.User");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchoolOrUniversityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudyField")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("RoleId");

                    b.HasIndex("StudentLevelId");

                    b.HasIndex("UniversityId");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("Server.Entities.Application", b =>
                {
                    b.HasOne("Server.Entities.ApplicationStatus", "ApplicationStatus")
                        .WithMany("Application")
                        .HasForeignKey("ApplicationStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.Scholarship", "Scholarship")
                        .WithMany("Application")
                        .HasForeignKey("ScholarshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.Student", "Student")
                        .WithMany("Application")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationStatus");

                    b.Navigation("Scholarship");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Server.Entities.ApplicationDocument", b =>
                {
                    b.HasOne("Server.Entities.Application", "Application")
                        .WithMany("ApplicationDocument")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Server.Entities.AuditLog", b =>
                {
                    b.HasOne("Server.Entities.User", "User")
                        .WithMany("AuditLog")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Entities.Feedback", b =>
                {
                    b.HasOne("Server.Entities.Scholarship", "Scholarship")
                        .WithMany("Feedback")
                        .HasForeignKey("ScholarshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.User", "User")
                        .WithMany("Feedback")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scholarship");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Entities.Notification", b =>
                {
                    b.HasOne("Server.Entities.User", "User")
                        .WithMany("Notification")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Entities.Scholarship", b =>
                {
                    b.HasOne("Server.Entities.AcademicYear", null)
                        .WithMany("Scholarship")
                        .HasForeignKey("AcademicYearId");

                    b.HasOne("Server.Entities.EligibilityCriteria", null)
                        .WithMany("Scholarship")
                        .HasForeignKey("EligibilityCriteriaId");

                    b.HasOne("Server.Entities.Provider", "Provider")
                        .WithMany("Scholarship")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.ScholarshipCategory", "ScholarshipCategory")
                        .WithMany("Scholarship")
                        .HasForeignKey("ScholarshipCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.ScholarshipType", "ScholarshipType")
                        .WithMany("Scholarship")
                        .HasForeignKey("ScholarshipTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("ScholarshipCategory");

                    b.Navigation("ScholarshipType");
                });

            modelBuilder.Entity("Server.Entities.ScholarshipAward", b =>
                {
                    b.HasOne("Server.Entities.Scholarship", "Scholarship")
                        .WithMany("ScholarshipAward")
                        .HasForeignKey("ScholarshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scholarship");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Server.Entities.UserActivityLog", b =>
                {
                    b.HasOne("Server.Entities.User", "User")
                        .WithMany("UserActivityLog")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Entities.Admin", b =>
                {
                    b.HasOne("Server.Entities.Role", "Role")
                        .WithMany("Admin")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Server.Entities.Provider", b =>
                {
                    b.HasOne("Server.Entities.Country", null)
                        .WithMany("Provider")
                        .HasForeignKey("CountryId");

                    b.HasOne("Server.Entities.Role", "Role")
                        .WithMany("Provider")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Server.Entities.Student", b =>
                {
                    b.HasOne("Server.Entities.Role", "Role")
                        .WithMany("Students")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.StudentLevel", "StudentLevel")
                        .WithMany("Student")
                        .HasForeignKey("StudentLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.University", null)
                        .WithMany("Student")
                        .HasForeignKey("UniversityId");

                    b.Navigation("Role");

                    b.Navigation("StudentLevel");
                });

            modelBuilder.Entity("Server.Entities.AcademicYear", b =>
                {
                    b.Navigation("Scholarship");
                });

            modelBuilder.Entity("Server.Entities.Application", b =>
                {
                    b.Navigation("ApplicationDocument");
                });

            modelBuilder.Entity("Server.Entities.ApplicationStatus", b =>
                {
                    b.Navigation("Application");
                });

            modelBuilder.Entity("Server.Entities.Country", b =>
                {
                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Server.Entities.EligibilityCriteria", b =>
                {
                    b.Navigation("Scholarship");
                });

            modelBuilder.Entity("Server.Entities.Role", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Provider");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Server.Entities.Scholarship", b =>
                {
                    b.Navigation("Application");

                    b.Navigation("Feedback");

                    b.Navigation("ScholarshipAward");
                });

            modelBuilder.Entity("Server.Entities.ScholarshipCategory", b =>
                {
                    b.Navigation("Scholarship");
                });

            modelBuilder.Entity("Server.Entities.ScholarshipType", b =>
                {
                    b.Navigation("Scholarship");
                });

            modelBuilder.Entity("Server.Entities.StudentLevel", b =>
                {
                    b.Navigation("Student");
                });

            modelBuilder.Entity("Server.Entities.University", b =>
                {
                    b.Navigation("Student");
                });

            modelBuilder.Entity("Server.Entities.User", b =>
                {
                    b.Navigation("AuditLog");

                    b.Navigation("Feedback");

                    b.Navigation("Notification");

                    b.Navigation("UserActivityLog");
                });

            modelBuilder.Entity("Server.Entities.Provider", b =>
                {
                    b.Navigation("Scholarship");
                });

            modelBuilder.Entity("Server.Entities.Student", b =>
                {
                    b.Navigation("Application");
                });
#pragma warning restore 612, 618
        }
    }
}
